# Thanks for downloading DeadByDaylight for Minecraft (Spigot) 1.12.2+

storageMethod: "mysql"

mysql:
  host:
  port:
  username:
  password:
  database:

# Do you want the plugin to send updates via MySQL to update the live webpage? (Changeds player status, player stats change even with this option disabled!)
submitData: true